### ISSUE TITLE
Unable to run the handler

### ISSUE THREAD

**Issue by abhinav-sachdeva** [ZenitechSoftware/lambda-node#6]
I've packed the function with a simple hello world handler but am unable to execute.
Getting the following error: 
Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at getNodeChildProcess (/var/task/node_modules/lambda-node-runtime/src/lambdaHandler.js:65:9)
    at module.exports (/var/task/node_modules/lambda-node-runtime/src/lambdaHandler.js:96:9)

**Comment by ghost** [comment]
Can you please provide the code?

**Comment by abhinav-sachdeva** [comment]
The index.js that holds the Lambda function is:
`module.exports.handler = (event, context, callback) => {
	callback(null,"hello world");
}`

Handler specified in the console : node_modules/lambda-node-runtime/index.handler
Env var set LAMBDA_NODE_HANDLER=index.handler

Project structure:
index.js (This hello world call here)
package.json
node_modules

**Comment by mykolasmolis** [comment]
Can you please check if:
- Lambda use Node version 6.10
- Lambda Timeout is at least 4 seconds (I would give 10 seconds just in case)
- Can you check that file at  `node_modules/lambda-node-runtime/.node/bin/node` has execution permission (`chmod +x node_modules/lambda-node-runtime/.node/bin/node`)

**Comment by abhinav-sachdeva** [comment]
- Lambda uses Node version 6.10 : YES
- Lambda Timeout is at 15 seconds
- File permissions : I'm on windows

**Comment by abhinav-sachdeva** [comment]
I'm certain that the file has execution permission, the error remains the same.

**Comment by mykolasmolis** [comment]
It must be lack of execute permissions on `node_modules/lambda-node-runtime/.node/bin/node` file. I removed the permissions end tried to run lambda function in Lambda and got this error:
```
Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at getNodeChildProcess (/var/task/test-lambda-function/node_modules/lambda-node-runtime/src/lambdaHandler.js:65:9)
    at module.exports (/var/task/test-lambda-function/node_modules/lambda-node-runtime/src/lambdaHandler.js:96:9)
```
It looks like when Node.js is downloaded on Windows the execute permission is not retained (most probably because Node.js executable for Linux is being downloaded).

Please follow these instructions to set `node_modules/lambda-node-runtime/.node/bin/node` execute permission on windows: https://www.quora.com/How-can-I-set-file-folder-permissions-to-755-or-644-in-Windows
